[project]
name = "s25-coopai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "anthropic>=0.45.2",
    "google-genai>=1.2.0",
    "openai>=1.63.0",
    "pandas>=2.2.3",
    "torch>=2.6.0",
]
